export const bootcamp = [
  {
    id: 1,
    title: "Silandra Alta Costura",
    web: "https://silandra.vercel.app/",
    img: "/assets/silandra.jpeg",
    alt: "Web App de Silandra Alta Costura",
    src: "https://github.com/SilviStani/Silandra",
    desc: "Responsive Web app para Casa de Alta Costura.",
  },
  {
    id: 2,
    title: "Portfolio",
    web: "react-portfolio-silvistani.vercel.app",
    img: "https://user-images.githubusercontent.com/90510746/206809662-801fbf30-7ab4-48f7-bb2d-e39e84cdb0e7.png",
    alt: "Portfolio personal de Silvina Staniszewski",
    src: " https://github.com/SilviStani/React-Portfolio",
    desc: "Pequeña descripción de mis trabajos y mis pasiones.",
  },
  {
    id: 3,
    title: "Walter Tapizados",
    web: "https://limpieza-tapizados-walter.vercel.app/",
    img: "/assets/Walter-tapizados.png",
    alt: "Web app de Limpieza de Tapizados en Chaco",
    desc: "Web limpieza de tapizados en Chaco y Corrientes",
    src: "https://github.com/SilviStani/Limpieza-Tapizados-Walter",
  },
  {
    id: 4,
    title: "Estetyczna Nadja Szewska",
    web: "https://estetyczna-nadja-szewska.vercel.app/",
    img: "/assets/introPage.jpg",
    alt: "Web app de página de estética",
    src: "https://github.com/SilviStani/Estetyczna-Nadja-Szewska",
    desc: "SPA de Estética corporal y facial. Servicio de belleza integral.",
  },
  {
    id: 5,
    title: "Delicias y Manjares",
    web: "https://deliciasymanjares.vercel.app/",
    img: "/assets/3.jpg",
    alt: "Web app de Delicias y Manjares",
    src: "https://github.com/SilviStani/deliciasymanjares",
    desc: "Las delicias mas exquisitas y frescas de todo Escobar. No dudes en probar :)",
  },
  {
    id: 6,
    title: "Cabañas Mirsú",
    web: "https://cabanasmirsu.vercel.app",
    img: "/assets/Cabanias-mirsu.png",
    alt: "Web app cabañas en Villa General Belgrano",
    src: "https://github.com/SilviStani/cabanias_mirsu",
    desc: "Cabañas en Villa General Belgrano. Mapa de ubicación, links a sitios de interés, sitios de necesidad.",
  },
  {
    id: 7,
    title: "VIPets",
    img: "https://user-images.githubusercontent.com/90510746/160607183-5527d9ec-bacf-458f-a48c-d89459f00a81.png",
    alt: "Proyecto final Henry, Full stack web developer",
    src: "https://github.com/Navito-py/PF-PuppyPalace",
    web: "",
    desc: "Proyecto individual para el bootcamp de 'Henry'.",
  },
  {
    id: 8,
    title: "Food*HenryApp",
    img: "https://user-images.githubusercontent.com/90510746/155239699-a0ab095e-cfb3-4a32-8756-e1f3b9e4d948.jpg",
    alt: "Proyecto individual para Henry Bootcamp",
    src: "https://github.com/SilviStani/Pi-Food",
    web: "",
    desc: "Proyecto individual para el bootcamp de 'Henry'.",
  },
  {
    id: 9,
    title: "Chronometer",
    img: "https://user-images.githubusercontent.com/90510746/148205845-1f650bfd-15ad-433c-839d-962786b50e83.png",
    alt: "Cronometro, parte de las practicas",
    src: "https://github.com/SilviStani/Chronometer-Countdown-Timer",
    web: "",
    desc: "A Single & Simple Chronometer pure redux",
  },

  {
    id: 10,
    title: "TodoList: Vacation",
    web: "",
    img: "https://user-images.githubusercontent.com/90510746/148145113-25ef5a46-17d7-4c5f-b9e0-07716ffc0b02.png",
    alt: "Lista de tareas, página de práctica vanilla javascript",
    src: "https://github.com/SilviStani/Vacation-TodoList",
    desc: "Una Todo list creada a puro vanilla javascript. Sus efectos y estilos en Css.",
  },
];
